events{}

http{
    # Rate limiting configuration
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=1r/m;

    upstream backend_api {
        server api1:8000;
        server api2:8000;
    }

    server {
        listen 80;

        location / {
            # apply the rate limit
            limit_req zone=api_limit burst=25 nodelay;

            proxy_pass http://backend_api;
        }
    }
}